# Generated by Django 5.1.2 on 2025-05-13 21:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mototaxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_mototaxi', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Conductores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=100)),
                ('fecha_de_creacion', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mototaxi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conductores.mototaxis')),
            ],
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_novedad', models.CharField(max_length=50)),
                ('tipo_novedad', models.CharField(choices=[('REPARACION', 'Reparacion'), ('ACTIVO', 'Activo'), ('SIN_REPARAR', 'Sin reparar'), ('OTRO', 'Otro')], max_length=500)),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conductores.conductores')),
                ('mototaxi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conductores.mototaxis')),
            ],
        ),
    ]
