# Generated by Django 5.1.2 on 2025-05-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='cedula',
            field=models.BigIntegerField(unique=True),
        ),
    ]
