# Generated by Django 5.1.2 on 2024-11-18 23:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='fecha_de_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
