# Generated by Django 5.1.2 on 2025-05-28 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0002_alter_conductores_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedades',
            name='fecha_novedad',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
