# Generated by Django 5.1.2 on 2024-11-19 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0002_alter_conductores_fecha_de_creacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mototaxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa_mototaxi', models.CharField(max_length=10, unique=True)),
                ('modelo', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='conductores',
            name='placa_mototaxi',
        ),
        migrations.AddField(
            model_name='conductores',
            name='mototaxi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conductores.mototaxis'),
        ),
    ]
