# Generated by Django 5.1.2 on 2024-11-27 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0003_mototaxis_remove_conductores_placa_mototaxi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='usuario',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='Novedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_novedad', models.CharField(max_length=50)),
                ('tipo_novedad', models.CharField(max_length=500)),
                ('mototaxi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conductores.mototaxis')),
            ],
        ),
    ]
