# Generated by Django 5.1.2 on 2025-05-13 18:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0004_alter_conductores_usuario_novedades'),
    ]

    operations = [
        migrations.AddField(
            model_name='novedades',
            name='conductor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conductores.conductores'),
        ),
        migrations.AddField(
            model_name='novedades',
            name='fecha_novedad',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='novedades',
            name='tipo_novedad',
            field=models.CharField(choices=[('REPARACION', 'Reparacion'), ('ACTIVO', 'Activo'), ('SIN_REPARAR', 'Sin reparar'), ('OTRO', 'Otro')], max_length=500),
        ),
    ]
