# Generated by Django 5.1.2 on 2025-05-13 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0005_novedades_conductor_novedades_fecha_novedad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novedades',
            name='fecha_novedad',
        ),
    ]
